"""Codomyrmex - A Modular, Extensible Coding Workspace.

This package provides a comprehensive suite of specialized modules organized in a
four-layer architecture for AI-assisted software development, code analysis,
testing, documentation generation, and workflow automation.
"""

__version__ = "1.2.3"

import os
import pkgutil
from pathlib import Path

from codomyrmex.logging_monitoring import get_logger

logger = get_logger(__name__)


def get_version() -> str:
    """Get the package version."""
    return __version__


def get_module_path() -> Path:
    """Get the absolute path to the package directory."""
    return Path(__file__).parent


def list_modules() -> list[str]:
    """List all available submodules in the package."""
    return [name for _, name, _ in pkgutil.iter_modules([str(get_module_path())])]


# Explicitly export major submodules for easier access
# Use lazy imports to avoid requiring all optional dependencies
_submodules = [
    "agentic_memory",
    "agents",
    "ai_gateway",
    "aider",
    "api",
    "audio",
    "auth",
    "autograd",
    "bio_simulation",
    "cache",
    "calendar_integration",
    "cerebrum",
    "ci_cd_automation",
    "cli",
    "cloud",
    "coding",
    "collaboration",
    "compression",
    "concurrency",
    "config_audits",
    "config_management",
    "config_monitoring",
    "container_optimization",
    "containerization",
    "cost_management",
    "crypto",
    "dark",
    "data_curation",
    "data_lineage",
    "data_visualization",
    "database_management",
    "defense",
    "demos",
    "dependency_injection",
    "deployment",
    "distillation",
    "distributed_training",
    "docs_gen",
    "documentation",
    "documents",
    "dpo",
    "edge_computing",
    "email",
    "embodiment",
    "encryption",
    "environment_setup",
    "eval_harness",
    "events",
    "evolutionary_ai",
    "examples",
    "exceptions",
    "feature_flags",
    "feature_store",
    "file_system",
    "finance",
    "formal_verification",
    "fpf",
    "git_analysis",
    "git_operations",
    "graph_rag",
    "ide",
    "identity",
    "image",
    "interpretability",
    "languages",
    "llm",
    "logging_monitoring",
    "logistics",
    "logit_processor",
    "lora",
    "maintenance",
    "market",
    "matmul_kernel",
    "meme",
    "ml_pipeline",
    "model_context_protocol",
    "model_merger",
    "model_ops",
    "module_template",
    "multimodal",
    "nas",
    "networking",
    "networks",
    "neural",
    "operating_system",
    "orchestrator",
    "pai_pm",
    "peft",
    "performance",
    "physical_management",
    "plugin_system",
    "privacy",
    "prompt_engineering",
    "quantization",
    "quantum",
    "relations",
    "release",
    "rlhf",
    "scrape",
    "search",
    "security",
    "semantic_router",
    "serialization",
    "simulation",
    "skills",
    "slm",
    "softmax_opt",
    "soul",
    "spatial",
    "ssm",
    "static_analysis",
    "synthetic_data",
    "system_discovery",
    "telemetry",
    "templating",
    "terminal_interface",
    "testing",
    "tests",
    "text_to_sql",
    "tokenizer",
    "tool_use",
    "tree_sitter",
    "utils",
    "validation",
    "vector_store",
    "video",
    "vision",
    "wallet",
    "website",
]


# Import submodules lazily with error handling
def __getattr__(name):
    """Lazy import submodules on first access."""
    if name in _submodules:
        import importlib

        try:
            module = importlib.import_module(f".{name}", __package__)
            globals()[name] = module
            return module
        except ImportError as e:
            raise ImportError(
                f"Failed to import {name}: {e}. You may need to install optional dependencies."
            ) from e
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


# Eager imports for convenience.
# These are the "always available" modules
try:
    from . import exceptions, utils
except ImportError as e:
    logger.debug("Optional eager imports unavailable: %s", e)

__all__ = [
    "agentic_memory",
    "agents",
    "ai_gateway",
    "aider",
    "api",
    "audio",
    "auth",
    "autograd",
    "bio_simulation",
    "cache",
    "calendar_integration",
    "cerebrum",
    "ci_cd_automation",
    "cli",
    "cloud",
    "coding",
    "collaboration",
    "compression",
    "concurrency",
    "config_audits",
    "config_management",
    "config_monitoring",
    "container_optimization",
    "containerization",
    "cost_management",
    "crypto",
    "dark",
    "data_curation",
    "data_lineage",
    "data_visualization",
    "database_management",
    "defense",
    "demos",
    "dependency_injection",
    "deployment",
    "distillation",
    "distributed_training",
    "docs_gen",
    "documentation",
    "documents",
    "dpo",
    "edge_computing",
    "email",
    "embodiment",
    "encryption",
    "environment_setup",
    "eval_harness",
    "events",
    "evolutionary_ai",
    "examples",
    "exceptions",
    "feature_flags",
    "feature_store",
    "file_system",
    "finance",
    "formal_verification",
    "fpf",
    "get_module_path",
    "get_version",
    "git_analysis",
    "git_operations",
    "graph_rag",
    "ide",
    "identity",
    "image",
    "interpretability",
    "languages",
    "list_modules",
    "llm",
    "logging_monitoring",
    "logistics",
    "logit_processor",
    "lora",
    "maintenance",
    "market",
    "matmul_kernel",
    "meme",
    "ml_pipeline",
    "model_context_protocol",
    "model_merger",
    "model_ops",
    "module_template",
    "multimodal",
    "nas",
    "networking",
    "networks",
    "neural",
    "operating_system",
    "orchestrator",
    "pai_pm",
    "peft",
    "performance",
    "physical_management",
    "plugin_system",
    "privacy",
    "prompt_engineering",
    "quantization",
    "quantum",
    "relations",
    "release",
    "rlhf",
    "scrape",
    "search",
    "security",
    "semantic_router",
    "serialization",
    "simulation",
    "skills",
    "slm",
    "softmax_opt",
    "soul",
    "spatial",
    "ssm",
    "static_analysis",
    "synthetic_data",
    "system_discovery",
    "telemetry",
    "templating",
    "terminal_interface",
    "testing",
    "tests",
    "text_to_sql",
    "tokenizer",
    "tool_use",
    "tree_sitter",
    "utils",
    "validation",
    "vector_store",
    "video",
    "vision",
    "wallet",
    "website",
]
