from enum import Enum


class Command(Enum):
    """Functional component: Command."""
    CHECK = "check"
    INFO = "info"
    MODULES = "modules"
    STATUS = "status"
    DOCTOR = "doctor"
    SHELL = "shell"
    CHAT = "chat"
    WORKFLOW = "workflow"
    PROJECT = "project"
    ORCHESTRATION = "orchestration"
    AI = "ai"
    ANALYZE = "analyze"
    BUILD = "build"
    MODULE = "module"
    FPF = "fpf"
    SKILLS = "skills"
    RUN = "run"
    PIPE = "pipe"
    BATCH = "batch"
    CHAIN = "chain"
    EXEC = "exec"
    MOD = "mod"
