/**
 * Reader-oriented documentation navigation.
 *
 * Module documentation is generated from the current docs tree so additions,
 * removals, and renamed modules cannot leave stale document IDs in this file.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Project Overview',
      link: {
        type: 'generated-index',
        title: 'Project Overview',
        description:
          'Learn about Codomyrmex, its architecture, and how to contribute.',
        slug: '/project-overview',
      },
      items: [
        'project/architecture',
        'project/CONTRIBUTING_TO_DOCUMENTATION',
        'project/contributing',
        'project/code-of-conduct',
        'project/license',
      ],
    },
    {
      type: 'category',
      label: 'Development Guides',
      link: {
        type: 'generated-index',
        title: 'Development Guides',
        description: 'Guides for developing and validating Codomyrmex.',
        slug: '/development-guides',
      },
      items: [
        'development/environment-setup',
        'project/TESTING_STRATEGY',
        'project/ERROR_HANDLING_LOGGING',
        'development/documentation-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      link: {
        type: 'generated-index',
        title: 'Codomyrmex Modules',
        description: 'Explore the current Codomyrmex module documentation.',
        slug: '/modules',
      },
      items: [{type: 'autogenerated', dirName: 'modules'}],
    },
  ],
};

module.exports = sidebars;
