/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Project Overview',
      link: {
        type: 'generated-index',
        title: 'Project Overview',
        description: 'Learn about the Codomyrmex project, how to contribute, and its core principles.',
        slug: '/project-overview'
      },
      items: [
        'project/architecture',
        'project/CONTRIBUTING_TO_DOCUMENTATION',
        'project/contributing',
        'project/code-of-conduct',
        'project/license',
      ],
    },
    {
      type: 'category',
      label: 'Development Guides',
      link: {
        type: 'generated-index',
        title: 'Development Guides',
        description: 'Guides for developers contributing to or working with Codomyrmex.',
        slug: '/development-guides'
      },
      items: [
        'development/environment-setup',
        'project/TESTING_STRATEGY',
        'project/ERROR_HANDLING_LOGGING',
        'development/documentation-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'Project Tutorials',
      link: {
        type: 'generated-index',
        title: 'Project Tutorials',
        description: 'General tutorials covering broad concepts or multi-module workflows within Codomyrmex.',
        slug: '/project-tutorials'
      },
      items: [
        // Add project-wide tutorials here, e.g.:
        // 'tutorials/understanding-mcp',
        // 'tutorials/creating-a-new-module',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      link: {
        type: 'generated-index',
        title: 'Codomyrmex Modules',
        description: 'Explore the capabilities of individual Codomyrmex modules.',
        slug: '/modules'
      },
      items: [
        {
          type: 'category',
          label: 'AI Code Editing',
          link: {type: 'doc', id: 'modules/ai_code_editing/README'},
          items: [
            'modules/ai_code_editing/api_specification',
            'modules/ai_code_editing/mcp_tool_specification',
            'modules/ai_code_editing/usage_examples',
            'modules/ai_code_editing/changelog',
            'modules/ai_code_editing/security',
            {
              type: 'category',
              label: 'Technical Overview',
              link: {type: 'doc', id: 'modules/ai_code_editing/docs/technical_overview'},
              items: []
            },
            {
              type: 'category',
              label: 'Tutorials',
              link: {
                type: 'generated-index',
                title: 'AI Code Editing Tutorials',
                slug: '/modules/ai-code-editing/tutorials'
              },
              items: [
                'modules/ai_code_editing/docs/tutorials/generate_code_snippet_tutorial',
                'modules/ai_code_editing/docs/tutorials/refactor_code_snippet_tutorial',
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Build Synthesis',
          link: {type: 'doc', id: 'modules/build_synthesis/README'},
          items: [
            'modules/build_synthesis/api_specification',
            'modules/build_synthesis/mcp_tool_specification',
            'modules/build_synthesis/usage_examples',
            'modules/build_synthesis/changelog',
            'modules/build_synthesis/security',
            {
              type: 'category',
              label: 'Technical Overview',
              link: {type: 'doc', id: 'modules/build_synthesis/docs/technical_overview'},
              items: []
            },
            {
              type: 'category',
              label: 'Tutorials',
              link: {
                type: 'generated-index',
                title: 'Build Synthesis Tutorials',
                slug: '/modules/build-synthesis/tutorials'
              },
              items: [
                'modules/build_synthesis/docs/tutorials/trigger_build_tutorial',
                'modules/build_synthesis/docs/tutorials/synthesize_code_component_tutorial',
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Code Execution Sandbox',
          link: {type: 'doc', id: 'modules/code_execution_sandbox/README'},
          items: [
            'modules/code_execution_sandbox/api_specification',
            'modules/code_execution_sandbox/mcp_tool_specification',
            'modules/code_execution_sandbox/usage_examples',
            'modules/code_execution_sandbox/changelog',
            'modules/code_execution_sandbox/security',
            {
              type: 'category',
              label: 'Technical Overview',
              link: {type: 'doc', id: 'modules/code_execution_sandbox/docs/technical_overview'},
              items: []
            },
            {
              type: 'category',
              label: 'Tutorials',
              link: {
                type: 'generated-index',
                title: 'Code Execution Sandbox Tutorials',
                slug: '/modules/code-execution-sandbox/tutorials'
              },
              items: [
                'modules/code_execution_sandbox/docs/tutorials/execute_code_tutorial',
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Data Visualization',
          link: {type: 'doc', id: 'modules/data_visualization/README'},
          items: [
            'modules/data_visualization/api_specification',
            'modules/data_visualization/mcp_tool_specification',
            'modules/data_visualization/usage_examples',
            'modules/data_visualization/changelog',
            'modules/data_visualization/security',
            {
              type: 'category',
              label: 'Technical Overview',
              link: {type: 'doc', id: 'modules/data_visualization/docs/technical_overview'},
              items: []
            },
            {
              type: 'category',
              label: 'Tutorials',
              link: {
                type: 'generated-index',
                title: 'Data Visualization Tutorials',
                slug: '/modules/data-visualization/tutorials'
              },
              items: [
                'modules/data_visualization/docs/tutorials/generating_a_bar_chart_tutorial',
                'modules/data_visualization/docs/tutorials/generating_a_histogram_tutorial',
                'modules/data_visualization/docs/tutorials/generating_a_line_plot_tutorial',
                'modules/data_visualization/docs/tutorials/generating_a_pie_chart_tutorial',
                'modules/data_visualization/docs/tutorials/generating_a_scatter_plot_tutorial',
                'modules/data_visualization/docs/tutorials/mcp_heatmap_tutorial',
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Documentation (Meta)',
          link: {type: 'doc', id: 'modules/documentation/index'},
          items: [
            'modules/documentation/api_specification',
            'modules/documentation/mcp_tool_specification',
            'modules/documentation/usage_examples',
            'modules/documentation/changelog',
            'modules/documentation/security',
            {
              type: 'category',
              label: 'Technical Overview',
              link: {type: 'doc', id: 'modules/documentation/docs/technical_overview'},
              items: [] 
            },
            {
              type: 'category',
              label: 'Tutorials',
              link: {
                type: 'generated-index',
                title: 'Documentation Module Tutorials',
                slug: '/modules/documentation-meta/tutorials' 
              },
              items: [
                'modules/documentation/docs/tutorials/example_tutorial',
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Environment Setup',
          link: {type: 'doc', id: 'modules/environment_setup/README'},
          items: [
            'modules/environment_setup/api_specification',
            'modules/environment_setup/mcp_tool_specification',
            'modules/environment_setup/usage_examples',
            'modules/environment_setup/changelog',
            'modules/environment_setup/security',
            {
              type: 'category',
              label: 'Technical Overview',
              link: {type: 'doc', id: 'modules/environment_setup/docs/technical_overview'},
              items: []
            },
            {
              type: 'category',
              label: 'Tutorials',
              link: {
                type: 'generated-index',
                title: 'Environment Setup Tutorials',
                slug: '/modules/environment-setup/tutorials'
              },
              items: [
                'modules/environment_setup/docs/tutorials/example_tutorial',
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Git Operations',
          link: {type: 'doc', id: 'modules/git_operations/README'},
          items: [
            'modules/git_operations/api_specification',
            'modules/git_operations/mcp_tool_specification',
            'modules/git_operations/usage_examples',
            'modules/git_operations/changelog',
            'modules/git_operations/security',
            {
              type: 'category',
              label: 'Technical Overview',
              link: {type: 'doc', id: 'modules/git_operations/docs/technical_overview'},
              items: []
            },
            {
              type: 'category',
              label: 'Tutorials',
              link: {
                type: 'generated-index',
                title: 'Git Operations Tutorials',
                slug: '/modules/git-operations/tutorials'
              },
              items: [
                'modules/git_operations/docs/tutorials/creating_feature_branch_tutorial',
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Logging & Monitoring',
          link: {type: 'doc', id: 'modules/logging_monitoring/README'},
          items: [
            'modules/logging_monitoring/api_specification',
            'modules/logging_monitoring/mcp_tool_specification',
            'modules/logging_monitoring/usage_examples',
            'modules/logging_monitoring/changelog',
            'modules/logging_monitoring/security',
            {
              type: 'category',
              label: 'Technical Overview',
              link: {type: 'doc', id: 'modules/logging_monitoring/docs/technical_overview'},
              items: []
            },
            {
              type: 'category',
              label: 'Tutorials',
              link: {
                type: 'generated-index',
                title: 'Logging & Monitoring Tutorials',
                slug: '/modules/logging-monitoring/tutorials'
              },
              items: [
                'modules/logging_monitoring/docs/tutorials/example_tutorial',
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Model Context Protocol',
          link: {type: 'doc', id: 'modules/model_context_protocol/README'},
          items: [
            'modules/model_context_protocol/api_specification',
            'modules/model_context_protocol/mcp_tool_specification',
            'modules/model_context_protocol/usage_examples',
            'modules/model_context_protocol/changelog',
            'modules/model_context_protocol/security',
            {
              type: 'category',
              label: 'Technical Overview',
              link: {type: 'doc', id: 'modules/model_context_protocol/docs/technical_overview'},
              items: []
            },
            {
              type: 'category',
              label: 'Tutorials',
              link: {
                type: 'generated-index',
                title: 'Model Context Protocol Tutorials',
                slug: '/modules/model-context-protocol/tutorials'
              },
              items: [
                'modules/model_context_protocol/docs/tutorials/example_tutorial',
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Pattern Matching',
          link: {type: 'doc', id: 'modules/pattern_matching/README'},
          items: [
            'modules/pattern_matching/pattern-matching-api-specification',
            'modules/pattern_matching/pattern-matching-mcp-tool-specification',
            'modules/pattern_matching/pattern-matching-usage-examples',
            'modules/pattern_matching/pattern-matching-changelog',
            'modules/pattern_matching/pattern-matching-security',
            {
              type: 'category',
              label: 'Technical Overview',
              link: {type: 'doc', id: 'modules/pattern_matching/docs/technical_overview'},
              items: []
            },
            {
              type: 'category',
              label: 'Tutorials',
              link: {
                type: 'generated-index',
                title: 'Pattern Matching Tutorials',
                slug: '/modules/pattern-matching/tutorials'
              },
              items: [
                'modules/pattern_matching/docs/tutorials/example_tutorial',
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Static Analysis',
          link: {type: 'doc', id: 'modules/static_analysis/README'},
          items: [
            'modules/static_analysis/api_specification',
            'modules/static_analysis/mcp_tool_specification',
            'modules/static_analysis/usage_examples',
            'modules/static_analysis/changelog',
            'modules/static_analysis/security',
            {
              type: 'category',
              label: 'Technical Overview',
              link: {type: 'doc', id: 'modules/static_analysis/docs/technical_overview'},
              items: []
            },
            {
              type: 'category',
              label: 'Tutorials',
              link: {
                type: 'generated-index',
                title: 'Static Analysis Tutorials',
                slug: '/modules/static-analysis/tutorials'
              },
              items: [
                'modules/static_analysis/docs/tutorials/example_tutorial',
              ]
            }
          ]
        },
      ],
    },
    {
      type: 'category',
      label: 'Development Setup',
      items: [
        'development/environment-setup',
      ]
    }
    // Add more top-level categories or docs here
  ],
};

module.exports = sidebars; 