/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Project Overview',
      link: {
        type: 'generated-index',
        title: 'Project Overview',
        description: 'Learn about the Codomyrmex project, how to contribute, and its core principles.',
        slug: '/project-overview'
      },
      items: [
        'project/architecture',
        'project/CONTRIBUTING_TO_DOCUMENTATION',
        'project/contributing',
        'project/code-of-conduct',
        'project/license',
      ],
    },
    {
      type: 'category',
      label: 'Development Guides',
      link: {
        type: 'generated-index',
        title: 'Development Guides',
        description: 'Guides for developers contributing to or working with Codomyrmex.',
        slug: '/development-guides'
      },
      items: [
        'development/environment-setup',
        'project/TESTING_STRATEGY',
        'project/ERROR_HANDLING_LOGGING',
        'development/documentation-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'Project Tutorials',
      link: {
        type: 'generated-index',
        title: 'Project Tutorials',
        description: 'General tutorials covering broad concepts or multi-module workflows within Codomyrmex.',
        slug: '/project-tutorials'
      },
      items: [
        // Add project-wide tutorials here, e.g.:
        // 'tutorials/understanding-mcp',
        // 'tutorials/creating-a-new-module',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      link: {
        type: 'generated-index',
        title: 'Codomyrmex Modules',
        description: 'Explore the capabilities of individual Codomyrmex modules.',
        slug: '/modules'
      },
      items: [
      ],
    },
    {
      type: 'category',
      label: 'Development Setup',
      items: [
        'development/environment-setup',
      ]
    }
    // Add more top-level categories or docs here
  ],
};

module.exports = sidebars; 