name: 📚 Documentation Issue
description: Report issues with documentation or suggest improvements
title: "[Docs]: "
labels: ["documentation", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! 📖

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      description: Please verify the following before submitting
      options:
        - label: I have searched for existing documentation issues
          required: true
        - label: I have read the [Contributing to Documentation guide](../docs/project/CONTRIBUTING_TO_DOCUMENTATION.md)
          required: false

  - type: dropdown
    id: issue_type
    attributes:
      label: Documentation Issue Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect information
        - Outdated content
        - Unclear/confusing content
        - Broken links
        - Formatting issues
        - Typo/grammar
        - Missing examples
        - Enhancement/improvement
        - Other (specify in description)
    validations:
      required: true

  - type: input
    id: page_url
    attributes:
      label: Page URL or Location
      description: Link to the documentation page or file path
      placeholder: "https://codomyrmex.readthedocs.io/... or src/codomyrmex/module_name/README.md"

  - type: dropdown
    id: module
    attributes:
      label: Related Module
      description: Which module's documentation is affected?
      options:
        - ai_code_editing
        - build_synthesis
        - code_execution_sandbox
        - data_visualization
        - documentation (website/meta)
        - environment_setup
        - git_operations
        - logging_monitoring
        - model_context_protocol
        - pattern_matching
        - static_analysis
        - system_discovery
        - terminal_interface
        - General/Project-wide
        - Other (specify in description)

  - type: textarea
    id: current_content
    attributes:
      label: Current Content
      description: Copy the current content that has issues (if applicable)
      render: markdown
      placeholder: Current documentation content...

  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: Describe the documentation issue in detail
      placeholder: |
        - What is wrong or missing?
        - What makes it confusing?
        - What specific improvements are needed?
    validations:
      required: true

  - type: textarea
    id: suggested_content
    attributes:
      label: Suggested Content
      description: Provide suggested changes or new content
      render: markdown
      placeholder: Suggested documentation content...

  - type: textarea
    id: examples_needed
    attributes:
      label: Examples Needed
      description: What code examples or use cases should be included?
      render: python
      placeholder: |
        # Example code that should be documented
        from codomyrmex import module
        result = module.function(param="example")

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      multiple: true
      options:
        - New users/beginners
        - Experienced developers
        - Contributors/maintainers
        - API users
        - CLI users
        - System administrators
        - Other (specify in description)

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation is this?
      multiple: true
      options:
        - API Reference
        - Tutorial/Guide
        - How-to Guide
        - Conceptual Overview
        - Installation Instructions
        - Configuration Guide
        - Troubleshooting
        - FAQ
        - Change Log
        - Contributing Guide
        - Other (specify in description)

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any additional context that would help
      placeholder: |
        - Where did you encounter this issue?
        - What were you trying to accomplish?
        - What other resources did you consult?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is fixing this documentation issue?
      options:
        - Low (minor improvement)
        - Medium (affects understanding)
        - High (blocks user success)
        - Critical (misleading/incorrect info)
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help improve this documentation?
      options:
        - label: I can write the documentation updates
        - label: I can review proposed changes
        - label: I can provide additional examples
        - label: I can help test the documentation with users

