"""Mixin for FPF orchestrator report generation and result export."""

import json
from pathlib import Path
from typing import Any

from codomyrmex.logging_monitoring import get_logger

logger = get_logger(__name__)


class FPFReportMixin:
    """Result export and markdown report generation.

    Requires ``output_dir`` and ``logger`` from the host class.
    """

    def export_results(self, analysis_results: dict[str, Any]) -> None:
        """Export all results to JSON and markdown.

        Args:
            analysis_results: Comprehensive analysis results
        """
        self.logger.info("Exporting results")

        json_path = self.output_dir / "comprehensive_analysis.json"
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(analysis_results, f, indent=2, default=str)
        self.logger.info("Exported JSON to %s", json_path)

        md_path = self.output_dir / "comprehensive_analysis.md"
        self._generate_markdown_report(analysis_results, md_path)
        self.logger.info("Exported markdown report to %s", md_path)

    def _generate_markdown_report(
        self, results: dict[str, Any], output_path: Path
    ) -> None:
        """Generate markdown report.

        Args:
            results: Analysis results
            output_path: Output file path
        """
        lines = [
            "# CEREBRUM Analysis of First Principles Framework",
            "",
            "## Overview",
            "",
            f"- **Total Patterns**: {results['fpf_statistics']['total_patterns']}",
            f"- **Total Concepts**: {results['fpf_statistics']['total_concepts']}",
            f"- **Total Relationships**: {results['fpf_statistics']['total_relationships']}",
            "",
            "## Case-Based Reasoning Analysis",
            "",
            f"- **Total Cases**: {results['case_based_reasoning']['total_cases']}",
            f"- **Case Base Size**: {results['case_based_reasoning']['case_base_size']}",
            "",
            "### Pattern Similarity Analysis",
            "",
        ]

        for pattern_id, data in list(
            results["case_based_reasoning"]["similarity_analysis"].items()
        )[:10]:
            lines.append(f"### Pattern {pattern_id}")
            lines.append(
                f"- **Predicted Importance**: {data.get('prediction', 'N/A'):.3f}"
            )
            lines.append(f"- **Confidence**: {data.get('confidence', 0):.3f}")
            lines.append(
                f"- **Similar Patterns Found**: {data.get('retrieved_count', 0)}"
            )
            lines.append("")

        lines.extend(
            [
                "## Bayesian Inference Analysis",
                "",
                f"- **Network Nodes**: {results['bayesian_inference']['network_nodes']}",
                f"- **Network Edges**: {results['bayesian_inference']['network_edges']}",
                "",
                "### Inference Results",
                "",
            ]
        )

        for pattern_id, data in list(
            results["bayesian_inference"]["inference_results"].items()
        )[:10]:
            if "importance_distribution" in data:
                lines.append(f"### Pattern {pattern_id}")
                dist = data["importance_distribution"]
                lines.append(f"- **High Importance**: {dist.get('high', 0):.3f}")
                lines.append(f"- **Medium Importance**: {dist.get('medium', 0):.3f}")
                lines.append(f"- **Low Importance**: {dist.get('low', 0):.3f}")
                lines.append(f"- **Most Likely**: {data.get('most_likely', 'N/A')}")
                lines.append("")

        lines.extend(
            [
                "## Active Inference Exploration",
                "",
                "### Exploration Path",
                "",
            ]
        )

        for step in results["active_inference"]["exploration_path"][:10]:
            lines.append(
                f"- **{step['pattern_id']}**: Action={step['action']}, "
                f"FE={step['free_energy']:.3f}, Importance={step['importance']:.3f}"
            )

        lines.extend(
            [
                "",
                "## Term Analysis",
                "",
                "### Important Terms",
                "",
            ]
        )

        for term, score, _count in results["term_analysis"]["important_terms"][:15]:
            lines.append(f"- **{term}**: Score={score:.3f}")

        lines.extend(
            [
                "",
                "---",
                "",
                "*Generated by CEREBRUM FPF Orchestrator*",
            ]
        )

        with open(output_path, "w", encoding="utf-8") as f:
            f.write("\n".join(lines))
