"""
Example asynchronous unit test function generated by PAI.
Demonstrates standard pytest-asyncio usage within the Codomyrmex codebase.
"""

import asyncio

import pytest


async def async_add(a: int, b: int) -> int:
    """
    An asynchronous addition function simulating I/O delay.

    Args:
        a: First integer
        b: Second integer

    Returns:
        The sum of a and b
    """
    await asyncio.sleep(0.01)
    return a + b


@pytest.mark.asyncio
@pytest.mark.unit
async def test_async_add_function():
    """
    Verify that the async_add function correctly sums two integers
    after an asynchronous delay.
    """
    # Arrange
    a = 10
    b = 20
    expected = 30

    # Act
    result = await async_add(a, b)

    # Assert
    assert result == expected


@pytest.mark.unit
def test_basic_assertion():
    """
    A simple synchronous test function to verify basic pytest functionality.
    """
    assert True is True
