#!/usr/bin/env python3
"""
Hermes Codebase Observer (Sentinel)
Uses Llama 3.2 to observe git history and surface recommendations.
"""

import subprocess
import datetime
from pathlib import Path
from codomyrmex.agents.hermes.hermes_client import HermesClient
from codomyrmex.agents import AgentRequest

import argparse
import time

class CodebaseObserver:
    """Perpetual codebase observer using Ollama for analysis."""

    def __init__(self, model: str = "llama3.2:latest") -> None:
        # Increase timeout for the Sentinel's deep analysis cycles
        self.client = HermesClient(config={"hermes_timeout": 3600})
        # Force Ollama backend
        self.client._backend = "ollama"
        self.client._active_backend = "ollama"
        self.client._ollama_model = model
        self.rec_dir = Path("recommendations")
        self.prompt_template = Path(__file__).parent.parent / "templates" / "observer_prompt.md"

    def get_git_context(self, limit=10):
        """Get recent git commits and diff summaries."""
        try:
            log = subprocess.check_output(
                ["git", "log", f"-n {limit}", "--pretty=format:%h - %s (%ad)", "--date=short"],
                text=True
            )
            summary = subprocess.check_output(
                ["git", "diff", "--stat", f"HEAD~{limit}", "HEAD"],
                text=True
            )
            return f"### Recent Commits:\n{log}\n\n### File Changes Summary:\n{summary}"
        except Exception as e:
            return f"Git context unavailable: {e}"

    def get_capability_context(self) -> str:
        """Retrieve context about available tools and skills."""
        context = ["## Available Codomyrmex Capabilities"]

        # Skill categories
        skills_dir = Path("src/codomyrmex/skills/skills/upstream")
        if skills_dir.exists():
            categories = sorted([d.name for d in skills_dir.iterdir() if d.is_dir() and not d.name.startswith(".")])
            context.append(f"- **Skill Categories**: {', '.join(categories)}")

        # Core MCP tools
        context.append("- **Core MCP Tools**: read_file, write_file, list_directory, analyze_python_file, search_codebase, git_status, git_diff, run_shell_command, gitnexus, desloppify")

        # Standards
        context.append("- **Standards**: Zero-Mock policy, modular separation (Foundation, Core, Service, Specialized), desloppify scoring.")

        return "\n".join(context)

    def run_cycle(self) -> None:
        """Run a single observation and recommendation cycle.

        Each cycle is **stateless**: a fresh session is created so that
        prior recommendations never pollute the context window.
        """
        start_time = time.time()
        try:
            # 1. Load system prompt
            system_prompt = ""
            if self.prompt_template.exists():
                system_prompt = self.prompt_template.read_text()

            # 2. Get context
            git_context = self.get_git_context()
            capability_context = self.get_capability_context()

            full_prompt = (
                f"{system_prompt}\n\n"
                f"{capability_context}\n\n"
                "### Recent Codebase Activity\n"
                f"{git_context}\n\n"
                "Analyze the trajectory of these changes. Identify architectural drift "
                "or technical debt. Surface exactly one high-impact recommendation, "
                "mentioning specific Tools or Skills to use.\n"
                "Remember: output MUST be under 1500 characters total."
            )

            print(
                f"[{datetime.datetime.now()}] Sentinel analyzing codebase "
                f"via {self.client._ollama_model}..."
            )

            # 3. Execute observation — use execute() with a FRESH request each
            #    cycle to avoid accumulating conversation history that causes
            #    the model to echo prior responses endlessly.
            request = AgentRequest(prompt=full_prompt)
            resp = self.client.execute(request, max_tokens=2048)

            if not resp.is_success():
                print(f"[{datetime.datetime.now()}] Observation failed: {resp.error}")
                return

            # 4. Save recommendation
            self.rec_dir.mkdir(parents=True, exist_ok=True)
            timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = self.rec_dir / f"REC_{timestamp}.md"

            duration = time.time() - start_time
            char_count = len(resp.content)

            rec_content = (
                f"# Recommendation {timestamp}\n\n"
                f"{resp.content}\n\n"
                "---\n"
                f"*Generated by Hermes Sentinel ({self.client._ollama_model}) "
                f"| Stateless Mode | {char_count} chars | {duration:.2f}s*\n"
            )

            filename.write_text(rec_content)
            print(
                f"[{datetime.datetime.now()}] Recommendation saved to "
                f"{filename} ({char_count} chars, {duration:.2f}s)"
            )

        except Exception as e:
            print(f"[{datetime.datetime.now()}] Error in observation cycle: {e}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Hermes Codebase Observer (Sentinel)")
    parser.add_argument("--loop", action="store_true", help="Run in a loop")
    parser.add_argument("--interval", type=int, default=3600, help="Interval between cycles in seconds (default 3600)")
    parser.add_argument("--model", type=str, default="llama3.2:latest", help="Ollama model to use")
    args = parser.parse_args()

    observer = CodebaseObserver(model=args.model)

    if args.loop:
        throttle = max(1, args.interval)
        print(f"[{datetime.datetime.now()}] Sentinel starting in loop mode (throttle: {throttle}s)...")
        while True:
            observer.run_cycle()
            if args.interval > 0:
                time.sleep(args.interval)
            else:
                # Perpetual mode still needs a tiny sub-second pause for system stability
                time.sleep(1)
    else:
        observer.run_cycle()
