#!/usr/bin/env python3
"""
Example: API - OpenAPI Specification Generation

Demonstrates:
- OpenAPI specification generation
- API schema definition
- Specification export (JSON/YAML)
- Integration with standardization submodules

Tested Methods:
- OpenAPIGenerator.generate_spec() - Verified in test_api.py::TestOpenAPIGenerator::test_generate_spec
- OpenAPISpecification.to_json() - Verified in test_api.py::TestOpenAPISpecification::test_to_json
- OpenAPISpecification.to_yaml() - Verified in test_api.py::TestOpenAPISpecification::test_to_yaml
"""
import sys
from pathlib import Path
from typing import Dict, Any

# Add src to path for importing Codomyrmex modules
current_dir = Path(__file__).parent
project_root = current_dir.parent.parent
sys.path.insert(0, str(project_root / "src"))

# Import common utilities
sys.path.insert(0, str(project_root / "examples" / "_common"))
from config_loader import load_config
from example_runner import ExampleRunner
from utils import print_section, print_results, print_success, print_error

from codomyrmex.api.openapi_generator import OpenAPISpecification, APISchema

def main():
    """Run the API example."""
    print_section("API Module Example")
    print("Demonstrating OpenAPI specification generation functionality")

    try:
        config = load_config(Path(__file__).parent / "config.yaml")
        print_success("Configuration loaded successfully")
    except Exception as e:
        print_error(f"Failed to load configuration: {e}")
        config = {}

    runner = ExampleRunner(__file__, config)
    runner.start()

    try:
        # Create a sample API schema
        sample_schema = APISchema(
            name="User",
            schema_type="object",
            properties={
                "id": {"type": "integer", "description": "User ID"},
                "name": {"type": "string", "description": "User name"},
                "email": {"type": "string", "format": "email", "description": "User email"}
            },
            required=["id", "name", "email"],
            example={"id": 1, "name": "John Doe", "email": "john@example.com"}
        )
        print_success("✓ Sample API schema created")

        # Create OpenAPI specification
        spec = OpenAPISpecification(version="3.0.3")
        spec.spec = {
            "openapi": "3.0.3",
            "info": {
                "title": "Codomyrmex API Example",
                "version": "1.0.0",
                "description": "Example API specification generated by Codomyrmex"
            },
            "paths": {
                "/users": {
                    "get": {
                        "summary": "Get users",
                        "responses": {
                            "200": {
                                "description": "List of users",
                                "content": {
                                    "application/json": {
                                        "schema": sample_schema.to_dict()
                                    }
                                }
                            }
                        }
                    }
                }
            },
            "components": {
                "schemas": {
                    "User": sample_schema.to_dict()
                }
            }
        }
        print_success("✓ OpenAPI specification created")

        # Export to JSON
        json_output = spec.to_json()
        print_success("✓ Specification exported to JSON")

        # Export to YAML
        try:
            yaml_output = spec.to_yaml()
            print_success("✓ Specification exported to YAML")
        except Exception as e:
            print_error(f"YAML export failed (PyYAML may not be installed): {e}")

        operations_summary = {
            "generator_initialized": True,
            "schema_created": True,
            "specification_created": True,
            "json_export_successful": True,
            "yaml_export_successful": "PyYAML" in str(yaml_output) if 'yaml_output' in locals() else False,
            "specification_version": spec.version,
            "paths_count": len(spec.spec.get("paths", {})),
            "schemas_count": len(spec.spec.get("components", {}).get("schemas", {}))
        }

        print_results(operations_summary, "Operations Summary")
        runner.validate_results(operations_summary)
        runner.save_results(operations_summary)
        runner.complete()

        print("\n✅ API example completed successfully!")
    except Exception as e:
        runner.error("API example failed", e)
        print_error(f"API example failed: {e}")
        sys.exit(1)

if __name__ == "__main__":
    main()

