#!/usr/bin/env python3
"""Generate auditable Colony Kernel policy truth tables from live constants."""

from __future__ import annotations

import argparse
import json
from dataclasses import fields
from pathlib import Path
from typing import Any

from codomyrmex.colony_kernel.actuation_gate import (
    _GATE_SCORE_EXECUTE,
    _GATE_SCORE_HOLD,
    _TRUST_HARD_FLOOR,
)
from codomyrmex.colony_kernel.models import (
    FalsificationSeverity,
    ResourceCost,
    recommendation_for_severity,
    severity_rank,
)
from codomyrmex.colony_kernel.resource_ledger import ResourceBudget


def build_tables() -> dict[str, Any]:
    dimensions = [field.name for field in fields(ResourceCost)]
    budget_fields = [field.name for field in fields(ResourceBudget) if field.name.startswith("max_")]
    severity = [
        {
            "severity": item.value,
            "rank": severity_rank(item),
            "recommendation": recommendation_for_severity(item),
        }
        for item in FalsificationSeverity
    ]
    source_multipliers = {"test": 1.5, "human": 2.0, "security": 1.5, "agent": 1.0, "runtime": 1.0}
    return {
        "generator": "scripts/generate_colony_kernel_truth_tables.py",
        "gate_boundaries": {
            "execute_minimum": _GATE_SCORE_EXECUTE,
            "hold_minimum": _GATE_SCORE_HOLD,
            "trust_hard_floor": _TRUST_HARD_FLOOR,
            "hard_overrides": ["budget", "sandbox_role", "trust_floor", "critical_finding"],
        },
        "budget_dimensions": {
            "resource_cost_fields": dimensions,
            "resource_budget_cap_fields": budget_fields,
            "count": len(dimensions),
            "standalone_budget_failure": "REFUSE",
            "integrated_budget_failure": "HOLD",
        },
        "severity_policy": severity,
        "source_multipliers": source_multipliers,
        "falsification_input_fields": [
            "agent_id", "action_type", "target", "rationale", "expected_outcome",
            "rollback_plan", "tests", "metrics", "scope", "dependencies", "evidence",
        ],
        "claim_boundaries": {
            "failure": "caller-reported adverse outcome or attested failed execution",
            "policy_rejection": "proposal rejected before execution",
            "risk": "prospective falsification finding",
            "caller_reported_unattested": "not execution verification or ground truth",
            "attested_execution": "signed receipt linked to one consumed authorization",
        },
    }


def render_markdown(tables: dict[str, Any]) -> str:
    lines = [
        "# Colony Kernel generated truth tables",
        "",
        "Generated from live production constants. Do not edit this file by hand.",
        "",
        "## Gate boundaries",
        "",
        "| Boundary | Value |",
        "|---|---:|",
    ]
    for key, value in tables["gate_boundaries"].items():
        lines.append(f"| {key} | `{value}` |" if not isinstance(value, list) else f"| {key} | `{', '.join(value)}` |")
    lines.extend(["", "## Budget dimensions", "", "| Dimension | Value |", "|---|---|"])
    budget = tables["budget_dimensions"]
    for key, value in budget.items():
        lines.append(f"| {key} | `{value}` |")
    lines.extend(["", "## Severity policy", "", "| Severity | Rank | Recommendation |", "|---|---:|---|"])
    for row in tables["severity_policy"]:
        lines.append(f"| {row['severity']} | {row['rank']} | {row['recommendation']} |")
    lines.extend(["", "## Source multipliers", "", "| Source | Multiplier |", "|---|---:|"])
    for key, value in tables["source_multipliers"].items():
        lines.append(f"| {key} | {value} |")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=Path("evaluations/colony_kernel"))
    args = parser.parse_args()
    tables = build_tables()
    args.output_dir.mkdir(parents=True, exist_ok=True)
    (args.output_dir / "truth_tables.json").write_text(
        json.dumps(tables, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (args.output_dir / "truth_tables.md").write_text(
        render_markdown(tables), encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
