#!/usr/bin/env python3
"""Scan repo roots for directories missing AGENTS.md and/or README.md.

Writes docs/plans/agents-readme-gap-report.md (Markdown) and prints summary.

Excludes: __pycache__, .git, node_modules, .venv, venv, dist, build, htmlcov,
.pytest_cache, .ruff_cache, .mypy_cache, .docusaurus, .tox, *.egg-info, .eggs,
vendor caches, and paths matching SUBSTRING_EXCLUDES.

Run from repo root: uv run python scripts/rasp_gap_report.py
"""

from __future__ import annotations

import os
from pathlib import Path

EXCLUDE_DIR_NAMES = frozenset(
    {
        "__pycache__",
        ".git",
        "node_modules",
        ".venv",
        "venv",
        "dist",
        "build",
        "htmlcov",
        ".pytest_cache",
        ".ruff_cache",
        ".mypy_cache",
        ".docusaurus",
        ".tox",
        ".eggs",
        ".cursor",
        ".claude",
        ".benchmarks",
    }
)

# Skip subtrees (path fragment after normalizing to forward slashes).
SUBSTRING_EXCLUDES = (
    "/.git/",
    "/node_modules/",
    "/__pycache__/",
    "/.venv/",
    "/venv/",
    "/htmlcov/",
    "/.pytest_cache/",
    "/.ruff_cache/",
    "/.mypy_cache/",
    "/.docusaurus/",
    "/.tox/",
    "/.eggs/",
    "/vendor/openfang/",
    "/.cursor/",
    "/.claude/plugins/cache/",
    # Ephemeral / generated — not RASP documentation targets
    "/.benchmarks/",
    "/scripts/output/",
    "/scripts/agents/hermes/output/",
    "/scripts/sair/output/",
)

ROOTS = ("src/codomyrmex", "docs", "projects", "scripts", "config", ".github")


def repo_root() -> Path:
    return Path(__file__).resolve().parent.parent


def norm_rel(path: Path, root: Path) -> str:
    return path.resolve().relative_to(root).as_posix()


def should_skip_dir(path: Path, root: Path) -> bool:
    name = path.name
    if name in EXCLUDE_DIR_NAMES:
        return True
    if name.endswith(".egg-info"):
        return True
    rel = "/" + norm_rel(path, root) + "/"
    return any(frag in rel for frag in SUBSTRING_EXCLUDES)


def iter_dirs_under(root: Path, base: Path):
    if not base.is_dir():
        return
    yield base
    for dirpath, dirnames, _files in os.walk(base, topdown=True):
        dp = Path(dirpath)
        dirnames[:] = [
            d
            for d in sorted(dirnames)
            if not should_skip_dir(dp / d, root)
        ]
        for d in dirnames:
            yield dp / d


def scan_root(root: Path, rel_root: str) -> list[tuple[str, bool, bool]]:
    """Return list of (relative_path, has_agents, has_readme)."""
    base = root / rel_root
    if not base.is_dir():
        return []
    rows: list[tuple[str, bool, bool]] = []
    for d in iter_dirs_under(root, base):
        rel = norm_rel(d, root)
        has_agents = (d / "AGENTS.md").is_file()
        has_readme = (d / "README.md").is_file()
        if not has_agents or not has_readme:
            rows.append((rel, has_agents, has_readme))
    return rows


def main() -> int:
    root = repo_root()
    out_path = root / "docs" / "plans" / "agents-readme-gap-report.md"

    by_root: dict[str, list[tuple[str, bool, bool]]] = {}
    for rr in ROOTS:
        by_root[rr] = scan_root(root, rr)

    lines: list[str] = [
        "# AGENTS.md / README.md gap report",
        "",
        "Auto-generated by `uv run python scripts/rasp_gap_report.py`. Refresh after bulk doc changes.",
        "",
        "## Inclusion rules",
        "",
        "- Roots: `src/codomyrmex/`, `docs/`, `projects/`, `scripts/`, `config/`, `.github/`.",
        "- Excluded directory names and path fragments: see `EXCLUDE_DIR_NAMES` and `SUBSTRING_EXCLUDES` in `scripts/rasp_gap_report.py`.",
        "",
        "## Summary",
        "",
    ]

    total_dirs = 0
    missing_agents = 0
    missing_readme = 0
    missing_both = 0
    for rr, rows in by_root.items():
        ta = sum(1 for _r, a, _re in rows if not a)
        tr = sum(1 for _r, _a, re in rows if not re)
        tb = sum(1 for _r, a, re in rows if not a and not re)
        total_dirs += len(rows)
        missing_agents += ta
        missing_readme += tr
        missing_both += tb
        lines.append(f"- **{rr}/**: dirs with any gap: {len(rows)}; missing AGENTS.md: {ta}; missing README.md: {tr}; missing both: {tb}")

    lines.extend(
        [
            "",
            f"- **Totals (rows = dirs missing at least one file)**: {total_dirs}; missing AGENTS.md: {missing_agents}; missing README.md: {missing_readme}; missing both: {missing_both}",
            "",
            "## Detail by root",
            "",
        ]
    )

    for rr, rows in by_root.items():
        if not rows:
            lines.append(f"### `{rr}/`")
            lines.append("")
            lines.append("(root missing or no gaps)")
            lines.append("")
            continue
        lines.append(f"### `{rr}/`")
        lines.append("")
        lines.append("| Directory | AGENTS.md | README.md |")
        lines.append("| --- | --- | --- |")
        for rel, a, r in sorted(rows, key=lambda x: x[0]):
            lines.append(
                f"| `{rel}` | {'yes' if a else '**no**'} | {'yes' if r else '**no**'} |"
            )
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out_path.relative_to(root)}")
    print(f"Summary: {total_dirs} dir-rows with gaps; both missing: {missing_both}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
