"""CLI agent implementation."""

from .handlers import (
    handle_agent_setup,
    handle_agent_test,
    handle_claude_check,
    handle_claude_execute,
    handle_claude_stream,
    handle_codex_check,
    handle_codex_execute,
    handle_codex_stream,
    handle_droid_config_show,
    handle_droid_start,
    handle_droid_status,
    handle_droid_stop,
    handle_gemini_chat_list,
    handle_gemini_chat_resume,
    handle_gemini_chat_save,
    handle_gemini_check,
    handle_gemini_execute,
    handle_gemini_stream,
    handle_info,
    handle_jules_check,
    handle_jules_command,
    handle_jules_execute,
    handle_jules_help,
    handle_jules_stream,
    handle_opencode_check,
    handle_opencode_execute,
    handle_opencode_init,
    handle_opencode_stream,
    handle_opencode_version,
)
