#!/usr/bin/env python3
"""Generate enhanced coverage reports from JSON data.

This script processes coverage.json and generates:
- HTML summary reports
- Markdown reports for PRs
- Module-by-module breakdown
"""

import argparse
import json
import sys
from pathlib import Path
from datetime import datetime


def load_coverage_json(path: Path) -> dict:
    """Load coverage.json file."""
    if not path.exists():
        return {}
    
    with open(path) as f:
        return json.load(f)


def generate_markdown_report(coverage_data: dict, output_dir: Path) -> None:
    """Generate a markdown coverage report."""
    report_path = output_dir / "coverage_report.md"
    
    with open(report_path, "w") as f:
        f.write("# 📊 Coverage Report\n\n")
        f.write(f"*Generated: {datetime.now().isoformat()}*\n\n")
        
        # Overall summary
        totals = coverage_data.get("totals", {})
        if totals:
            percent = totals.get("percent_covered", 0)
            f.write("## Summary\n\n")
            f.write(f"- **Total Coverage**: {percent:.1f}%\n")
            f.write(f"- **Covered Lines**: {totals.get('covered_lines', 0)}\n")
            f.write(f"- **Missing Lines**: {totals.get('missing_lines', 0)}\n")
            f.write(f"- **Total Lines**: {totals.get('num_statements', 0)}\n\n")
        
        # Per-file breakdown (top 10 lowest coverage)
        files = coverage_data.get("files", {})
        if files:
            f.write("## Files Needing Attention\n\n")
            f.write("| File | Coverage | Missing Lines |\n")
            f.write("|------|----------|---------------|\n")
            
            # Sort by coverage percentage
            sorted_files = sorted(
                files.items(),
                key=lambda x: x[1].get("summary", {}).get("percent_covered", 100)
            )
            
            for file_path, file_data in sorted_files[:10]:
                summary = file_data.get("summary", {})
                percent = summary.get("percent_covered", 0)
                missing = summary.get("missing_lines", 0)
                # Shorten path
                short_path = file_path.split("src/")[-1] if "src/" in file_path else file_path
                f.write(f"| `{short_path}` | {percent:.1f}% | {missing} |\n")
        
        f.write("\n---\n")
        f.write("*Report generated by generate_coverage_report.py*\n")
    
    print(f"✅ Generated: {report_path}")


def generate_report(repo_root: Path, output_dir: Path = None) -> int:
    """Generate coverage reports."""
    print("📊 Generating coverage report...\n")
    
    if output_dir is None:
        output_dir = repo_root / "output"
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Find coverage.json
    coverage_path = repo_root / "coverage.json"
    if not coverage_path.exists():
        print("⚠️  coverage.json not found")
        return 1
    
    coverage_data = load_coverage_json(coverage_path)
    
    if not coverage_data:
        print("⚠️  Empty coverage data")
        return 1
    
    generate_markdown_report(coverage_data, output_dir)
    
    # Print summary
    totals = coverage_data.get("totals", {})
    if totals:
        percent = totals.get("percent_covered", 0)
        print(f"\n📈 Coverage: {percent:.1f}%")
        
        if percent < 70:
            print("⚠️  Coverage below 70% threshold")
        elif percent < 80:
            print("✅ Coverage meets minimum threshold")
        else:
            print("🎉 Excellent coverage!")
    
    return 0


def main():
    parser = argparse.ArgumentParser(description="Generate coverage reports")
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=Path.cwd(),
        help="Repository root directory"
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output directory for reports"
    )
    
    args = parser.parse_args()
    
    return generate_report(args.repo_root, args.output)


if __name__ == "__main__":
    sys.exit(main())
