/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But we can create a sidebar manually
  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Project Overview',
      items: [
        'project/contributing',
        'project/code-of-conduct',
        'project/license',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      link: {
        type: 'generated-index',
        title: 'Codomyrmex Modules',
        description: 'Learn about the different modules in the Codomyrmex project.',
        slug: '/category/modules'
      },
      items: [
        // This section will be populated later, e.g.:
        // 'modules/build_synthesis/index',
        {
          type: 'category',
          label: 'AI Code Editing',
          link: {type: 'doc', id: 'modules/ai_code_editing/ai-code-editing-index'},
          items: [
            'modules/ai_code_editing/ai-code-editing-api-specification',
            'modules/ai_code_editing/ai-code-editing-mcp-tool-specification',
            'modules/ai_code_editing/ai-code-editing-usage-examples',
            'modules/ai_code_editing/ai-code-editing-changelog',
            'modules/ai_code_editing/ai-code-editing-security',
            {
              type: 'category',
              label: 'Detailed Docs & Tutorials',
              link: {type: 'doc', id: 'modules/ai_code_editing/docs/ai-code-editing-module-docs-index'},
              items: [
                'modules/ai_code_editing/docs/ai-code-editing-technical-overview',
                {
                  type: 'category',
                  label: 'Tutorials',
                  link: {type: 'doc', id: 'modules/ai_code_editing/docs/tutorials/ai-code-editing-tutorials-index'},
                  items: [
                    'modules/ai_code_editing/docs/tutorials/ai-code-editing-example-tutorial',
                  ]
                }
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Static Analysis',
          link: {type: 'doc', id: 'modules/static_analysis/static-analysis-index'},
          items: [
            'modules/static_analysis/static-analysis-api-specification',
            'modules/static_analysis/static-analysis-mcp-tool-specification',
            'modules/static_analysis/static-analysis-usage-examples',
            'modules/static_analysis/static-analysis-changelog',
            'modules/static_analysis/static-analysis-security',
            {
              type: 'category',
              label: 'Detailed Docs & Tutorials',
              link: {type: 'doc', id: 'modules/static_analysis/docs/static-analysis-module-docs-index'},
              items: [
                'modules/static_analysis/docs/static-analysis-technical-overview',
                {
                  type: 'category',
                  label: 'Tutorials',
                  link: {type: 'doc', id: 'modules/static_analysis/docs/tutorials/static-analysis-tutorials-index'},
                  items: [
                    'modules/static_analysis/docs/tutorials/static-analysis-example-tutorial',
                  ]
                }
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Build Synthesis',
          link: {type: 'doc', id: 'modules/build_synthesis/build-synthesis-index'},
          items: [
            'modules/build_synthesis/build-synthesis-api-specification',
            'modules/build_synthesis/build-synthesis-mcp-tool-specification',
            'modules/build_synthesis/build-synthesis-usage-examples',
            'modules/build_synthesis/build-synthesis-changelog',
            'modules/build_synthesis/build-synthesis-security',
            {
              type: 'category',
              label: 'Detailed Docs & Tutorials',
              link: {type: 'doc', id: 'modules/build_synthesis/docs/build-synthesis-module-docs-index'},
              items: [
                'modules/build_synthesis/docs/build-synthesis-technical-overview',
                {
                  type: 'category',
                  label: 'Tutorials',
                  link: {type: 'doc', id: 'modules/build_synthesis/docs/tutorials/build-synthesis-tutorials-index'},
                  items: [
                    'modules/build_synthesis/docs/tutorials/build-synthesis-example-tutorial',
                  ]
                }
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Code Execution Sandbox',
          link: {type: 'doc', id: 'modules/code_execution_sandbox/code-execution-sandbox-index'},
          items: [
            'modules/code_execution_sandbox/code-execution-sandbox-api-specification',
            'modules/code_execution_sandbox/code-execution-sandbox-mcp-tool-specification',
            'modules/code_execution_sandbox/USAGE_EXAMPLES',
            'modules/code_execution_sandbox/code-execution-sandbox-changelog',
            'modules/code_execution_sandbox/code-execution-sandbox-security',
            {
              type: 'category',
              label: 'Detailed Docs & Tutorials',
              link: {type: 'doc', id: 'modules/code_execution_sandbox/docs/index'},
              items: [
                'modules/code_execution_sandbox/docs/technical_overview',
                {
                  type: 'category',
                  label: 'Tutorials',
                  link: {type: 'doc', id: 'modules/code_execution_sandbox/docs/tutorials/index'},
                  items: [
                    'modules/code_execution_sandbox/docs/tutorials/example_tutorial',
                  ]
                }
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Data Visualization',
          link: {type: 'doc', id: 'modules/data_visualization/index'},
          items: [
            'modules/data_visualization/api_specification',
            'modules/data_visualization/mcp_tool_specification',
            'modules/data_visualization/usage_examples',
            'modules/data_visualization/changelog',
            'modules/data_visualization/security',
            {
              type: 'category',
              label: 'Detailed Docs & Tutorials',
              link: {type: 'doc', id: 'modules/data_visualization/docs/index'},
              items: [
                'modules/data_visualization/docs/technical_overview',
                {
                  type: 'category',
                  label: 'Tutorials',
                  link: {type: 'doc', id: 'modules/data_visualization/docs/tutorials/index'},
                  items: [
                    'modules/data_visualization/docs/tutorials/example_tutorial',
                  ]
                }
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Documentation Module (Meta)',
          link: {type: 'doc', id: 'modules/documentation/index'},
          items: [
            'modules/documentation/api_specification',
            'modules/documentation/mcp_tool_specification',
            'modules/documentation/usage_examples',
            'modules/documentation/changelog',
            'modules/documentation/security',
            {
              type: 'category',
              label: 'Detailed Docs & Tutorials',
              link: {type: 'doc', id: 'modules/documentation/docs/index'},
              items: [
                'modules/documentation/docs/technical_overview',
                {
                  type: 'category',
                  label: 'Tutorials',
                  link: {type: 'doc', id: 'modules/documentation/docs/tutorials/index'},
                  items: [
                    'modules/documentation/docs/tutorials/example_tutorial',
                  ]
                }
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Environment Setup',
          link: {type: 'doc', id: 'modules/environment_setup/index'},
          items: [
            'modules/environment_setup/api_specification',
            'modules/environment_setup/mcp_tool_specification',
            'modules/environment_setup/usage_examples',
            'modules/environment_setup/changelog',
            'modules/environment_setup/security',
            {
              type: 'category',
              label: 'Detailed Docs & Tutorials',
              link: {type: 'doc', id: 'modules/environment_setup/docs/index'},
              items: [
                'modules/environment_setup/docs/technical_overview',
                {
                  type: 'category',
                  label: 'Tutorials',
                  link: {type: 'doc', id: 'modules/environment_setup/docs/tutorials/index'},
                  items: [
                    'modules/environment_setup/docs/tutorials/example_tutorial',
                  ]
                }
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Git Operations',
          link: {type: 'doc', id: 'modules/git_operations/index'},
          items: [
            'modules/git_operations/api_specification',
            'modules/git_operations/mcp_tool_specification',
            'modules/git_operations/usage_examples',
            'modules/git_operations/changelog',
            'modules/git_operations/security',
            {
              type: 'category',
              label: 'Detailed Docs & Tutorials',
              link: {type: 'doc', id: 'modules/git_operations/docs/index'},
              items: [
                'modules/git_operations/docs/technical_overview',
                {
                  type: 'category',
                  label: 'Tutorials',
                  link: {type: 'doc', id: 'modules/git_operations/docs/tutorials/index'},
                  items: [
                    'modules/git_operations/docs/tutorials/example_tutorial',
                  ]
                }
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Logging & Monitoring',
          link: {type: 'doc', id: 'modules/logging_monitoring/index'},
          items: [
            'modules/logging_monitoring/api_specification',
            'modules/logging_monitoring/mcp_tool_specification',
            'modules/logging_monitoring/usage_examples',
            'modules/logging_monitoring/changelog',
            'modules/logging_monitoring/security',
            {
              type: 'category',
              label: 'Detailed Docs & Tutorials',
              link: {type: 'doc', id: 'modules/logging_monitoring/docs/index'},
              items: [
                'modules/logging_monitoring/docs/technical_overview',
                {
                  type: 'category',
                  label: 'Tutorials',
                  link: {type: 'doc', id: 'modules/logging_monitoring/docs/tutorials/index'},
                  items: [
                    'modules/logging_monitoring/docs/tutorials/example_tutorial',
                  ]
                }
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'Model Context Protocol',
          link: {type: 'doc', id: 'modules/model_context_protocol/model-context-protocol-index'},
          items: [
            'modules/model_context_protocol/model-context-protocol-api-specification',
            'modules/model_context_protocol/model-context-protocol-mcp-tool-specification',
            'modules/model_context_protocol/model-context-protocol-usage-examples',
            'modules/model_context_protocol/model-context-protocol-changelog',
            'modules/model_context_protocol/model-context-protocol-security',
            {
              type: 'category',
              label: 'Detailed Docs & Tutorials',
              link: {type: 'doc', id: 'modules/model_context_protocol/docs/model-context-protocol-module-docs-index'},
              items: [
                'modules/model_context_protocol/docs/model-context-protocol-technical-overview',
                {
                  type: 'category',
                  label: 'Tutorials',
                  link: {type: 'doc', id: 'modules/model_context_protocol/docs/tutorials/model-context-protocol-tutorials-index'},
                  items: [
                    'modules/model_context_protocol/docs/tutorials/model-context-protocol-example-tutorial',
                  ]
                }
              ]
            }
          ]
        },
      ],
    },
    {
      type: 'category',
      label: 'Development Setup',
      items: [
        'development/environment-setup',
      ]
    }
    // Add more top-level categories or docs here
  ],
};

module.exports = sidebars; 